export const surpriseMeText = [
  'avocado',
  'cat playing checkers',
  'teddy bears',
  'chess',
  'digital art',
  "tiny surf boards",
  'fish ',
  'astronaut',
  'dark background',
  'a stained glass window',
  'a pencil',
  'lounge area',
  'giant hamburger',
  'pearl earring',
  'annoyed cat',
  'fox',
  'a bowl of soup ',
  'yellow wall',
  'sunset',
  'Tskybridge',
  'rainbow',
  'A comic book cover',
  'colorful powder',
  'Samoyed dog',
  'white fur monster',
  "headphones",
  'A Samurai',
  'young woman',
];